FROM postgres
WORKDIR /docker-entrypoint-initdb.d
ADD schema.sql /docker-entrypoint-initdb.d
#Uncomment this line if you need to access the database from your local machine. Uncomment lines in docker/docker-compose.yml as well.
#EXPOSE 5432